spring:
  profiles:
    active: dev

camel:
  springboot:
    shutdowntimeout: 5
  health.indicator.enabled: true

management:
  security:
    enabled: false
  endpoint:
    health:
      show-details: "ALWAYS"

healthUrl: "http://localhost:8080/actuator/health"

---

spring:
  profiles: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/srajgopalanDB
    username: postgres
    password: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: <username>
    password: <password>
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true

mailFrom: <from>
mailTo: <to>

message: dev
table: items

startRoute: timer:myTimer?period=10
fromRoute: file:/tmp/camel/input?delete=true&readLock=none&moveFailed=error
toRoute1: file:/tmp/camel/output
toRoute2: jdbc:dataSource
toRoute3: file:/tmp/camel/output?fileName=success.txt
healthRoute: timer:health?period=10s

---

spring:
  profiles: mock
  mail:
    host: smtp.gmail.com
    port: 587
    username: <username>
    password: <password>
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true

mailFrom: <from>
mailTo: <to>

message: mock
table: items

startRoute: direct:input
fromRoute: file:/tmp/camel/input?delete=true&readLock=none
toRoute1: mock:output
toRoute2: mock:output2
toRoute3: mock:output3
healthRoute: direct:health

---

spring:
  profiles: uat
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc://localhost:5432/srajgopalanDB
    username: postgres
    password: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: <username>
    password: <password>
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true

mailFrom: <from>
mailTo: <to>

message: uat
table: items

startRoute: timer:myTimer?period=10
fromRoute: file:/tmp/camel/input?delete=true&readLock=none
toRoute1: file:/tmp/camel/output
toRoute2: jdbc:dataSource
toRoute3: file:/tmp/camel/output?fileName=success.txt
healthRoute: timer:health?period=10s

---

spring:
  profiles: prd
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc://localhost:5432/srajgopalanDB
    username: postgres
    password: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: <username>
    password: <password>
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true

mailFrom: <from>
mailTo: <to>

message: prd
table: items

startRoute: timer:myTimer?period=10
fromRoute: file:/tmp/camel/input?delete=true&readLock=none
toRoute1: file:/tmp/camel/output
toRoute2: jdbc:dataSource
toRoute3: file:/tmp/camel/output?fileName=success.txt
healthRoute: timer:health?period=10s

---