spring:
  profiles:
    active: dev

camel:
  springboot:
    shutdowntimeout: 5

---

spring:
  profiles: dev

message: dev

startRoute: timer:myTimer?period=10
fromRoute: file:/tmp/camel/input?delete=true&readLock=none
toRoute1: file:/tmp/camel/output

---

spring:
  profiles: uat

message: uat

startRoute: timer:myTimer?period=10s
fromRoute: file:/tmp/camel/input?delete=true&readLock=none
toRoute1: file:/tmp/camel/output

---

spring:
  profiles: prd

message: prd

startRoute: timer:myTimer?period=10s
fromRoute: file:/tmp/camel/input?delete=true&readLock=none
toRoute1: file:/tmp/camel/output

---