spring:
  profiles:
    active: dev

camel:
  springboot:
    shutdowntimeout: 5

---

spring:
  profiles: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/srajgopalanDB
    username: postgres
    password: postgres

message: dev
table: items

startRoute: timer:myTimer?period=10
fromRoute: file:/tmp/camel/input?delete=true&readLock=none&moveFailed=error
toRoute1: file:/tmp/camel/output
toRoute2: jdbc:dataSource
toRoute3: file:/tmp/camel/output?fileName=success.txt

---

spring:
  profiles: mock

message: mock
table: items

startRoute: direct:input
fromRoute: file:/tmp/camel/input?delete=true&readLock=none
toRoute1: mock:output
toRoute2: mock:output2
toRoute3: mock:output3

---

spring:
  profiles: uat
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc://localhost:5432/srajgopalanDB
    username: postgres
    password: postgres

message: uat
table: items

startRoute: timer:myTimer?period=10
fromRoute: file:/tmp/camel/input?delete=true&readLock=none
toRoute1: file:/tmp/camel/output
toRoute2: jdbc:dataSource
toRoute3: file:/tmp/camel/output?fileName=success.txt

---

spring:
  profiles: prd
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc://localhost:5432/srajgopalanDB
    username: postgres
    password: postgres


message: prd
table: items

startRoute: timer:myTimer?period=10
fromRoute: file:/tmp/camel/input?delete=true&readLock=none
toRoute1: file:/tmp/camel/output
toRoute2: jdbc:dataSource
toRoute3: file:/tmp/camel/output?fileName=success.txt

---